pipeline {
    agent any

    tools {nodejs "NodeJS"}

    environment {
        PROJECT_PATH="${env.JENKINS_HOME}/workspace/training-2/testing-strategy-3"
        SCRIPTS_PATH="${PROJECT_PATH}/scripts"
        REPORT_PATH="${PROJECT_PATH}/e2e-web/cypress/cucumber-json"
        DEV="dev"
        ALPHA="alpha"
        PREPROD="preprod"
        PROD="prod"
    }

    stages {
        stage('Build') {
           steps {
                dir("${SCRIPTS_PATH}") {
                    sh """
                    echo "Build"
                    ./application-management.sh start&
                    """
                }
            }
        }
        stage('Test environment DEV') {
            steps {
                dir("${PROJECT_PATH}/e2e-web") {
                   sh """
                    echo "Test"
                    npm install
                    npm run test
                    """
                }
            }
        }
        stage('Report') {
            steps {
                dir("${SCRIPTS_PATH}") {
                   sh """
                    echo "Report"
                    ./report.sh generate DEV
                    """
                    dir("folder") {
                      publishHTML (target : [allowMissing: false,
                       alwaysLinkToLastBuild: true,
                       keepAll: true,
                       reportDir: 'reports',
                       reportFiles: "${REPORT_PATH}",
                       reportName: 'My Reports',
                       reportTitles: 'The Report'])
                    }
                    
                }
            }
        }
        stage('Deployment') {
            steps {
                dir("${SCRIPTS_PATH}") {
                   sh """
                    echo "Deployment"
                    """
                }
            }
        }
    }
}
