pipeline {
    agent any

    tools {nodejs "NodeJS"}

    environment {
        PROJECT_PATH="${env.JENKINS_HOME}/workspace/training-2/testing-strategy-3"
        SCRIPTS_PATH="${PROJECT_PATH}/scripts"
        DEV="dev"
        ALPHA="alpha"
        PREPROD="preprod"
        PROD="prod"
    }

    stages {
        stage('Build') {
           steps {
                dir("${SCRIPTS_PATH}") {
                    sh """
                    echo "Build"
                    ./application-management.sh start&
                    """
                }
            }
        }
        stage('Test environment DEV') {
            steps {
                dir("${PROJECT_PATH}/e2e-web") {
                   sh """
                    echo "Test"
                    npm install
                    npm run test
                    """
                }
            }
        }
        stage('Report') {
            steps {
                dir("${SCRIPTS_PATH}") {
                   sh """
                    echo "Report"
                    ./report.sh generate
                    """
                }
            }
        }
        stage('Deployment') {
            steps {
                dir("${SCRIPTS_PATH}") {
                   sh """
                    echo "Deployment"
                    """
                }
            }
        }
    }
}
